// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $about from "./routes/about.tsx";
import * as $api_convert from "./routes/api/convert.ts";
import * as $help from "./routes/help.tsx";
import * as $index from "./routes/index.tsx";
import * as $ConversionForm from "./islands/ConversionForm.tsx";
import * as $ConversionHistory from "./islands/ConversionHistory.tsx";
import * as $FileUploader from "./islands/FileUploader.tsx";
import * as $Footer from "./islands/Footer.tsx";
import * as $LanguageContext from "./islands/LanguageContext.tsx";
import * as $LanguageSwitcher from "./islands/LanguageSwitcher.tsx";
import * as $ProgressIndicator from "./islands/ProgressIndicator.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/about.tsx": $about,
    "./routes/api/convert.ts": $api_convert,
    "./routes/help.tsx": $help,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/ConversionForm.tsx": $ConversionForm,
    "./islands/ConversionHistory.tsx": $ConversionHistory,
    "./islands/FileUploader.tsx": $FileUploader,
    "./islands/Footer.tsx": $Footer,
    "./islands/LanguageContext.tsx": $LanguageContext,
    "./islands/LanguageSwitcher.tsx": $LanguageSwitcher,
    "./islands/ProgressIndicator.tsx": $ProgressIndicator,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
